name: Release Note

on:
  push:
    tags: 'v*'

jobs:
  generate:
    name: Generate
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 18

      - name: Setup git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - uses: actions/github-script@v6
        id: git-cliff
        with:
          result-encoding: string
          script: |
            const { stdout } = await exec.getExecOutput('git', ['cliff', '-l', '--strip', 'header'])
            return stdout
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: ${{ steps.git-cliff.outputs.result }}
