name: Testing

on:
  push:
  pull_request:

jobs:
  common:
    name: Check code format & type errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm format:check
      - run: pnpm typecheck

  edge:
    needs: [common]
    name: Edge Runtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test:edge

  node:
    needs: [common]
    name: Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test:node
